name: Publish

on:
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          make setup_dev

      - name: Run pytest (unit tests) and bandit (security test)
        run: |
          make test

      - name: Install the package to make sure nothing is randomly broken
        run: |
          make install

  publish-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7


      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: create python package
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull origin main
          pip install setuptools wheel twine
          python -m setup sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}


  update-brew:
    needs: publish-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: publish brew
        run: |
          sleep 5m
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pip install homebrew-pypi-poet
          pip install aws-allowlister -U
          git fetch origin
          git checkout --track origin/main
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          git pull origin $latest_tag
          poet -f aws-allowlister > HomebrewFormula/aws-allowlister.rb
          git add .
          git commit -m "update brew formula" aws_allowlister/bin/cli.py HomebrewFormula/aws-allowlister.rb || echo "No brew changes to commit"
          git push -u origin main
